# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - sprintplanapi

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      
      - name: Install Python Libs
        run: |
          python -m pip install --upgrade pip
          pip install pandas matplotlib flask flask-cors
    
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_560621D6E6754AD8AE7416B7844D996E }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_6A9D7F5EC8C441179FA2DBBAA3A1E063 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_B08B3EE41452401B9D600D6AA4BC4FD5 }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'sprintplanapi'
          slot-name: 'Production'          
